version: '3'
services:
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
        logging:
          driver: awslogs
          options: 
            awslogs-group: rabbitmq
            awslogs-region: sa-east-1
            awslogs-stream-prefix: rabbitmq
    # mybudget-service-registry:
    #     image: victorhugofranca/mybudget-service-registry
    #     container_name: mybudget-service-registry
    #     ports:
    #         - "8761:8761"
    #     logging:
    #       driver: awslogs
    #       options: 
    #         awslogs-group: mybudget-service-registry
    #         awslogs-region: sa-east-1
    #         awslogs-stream-prefix: mybudget-service-registry
    # mybudget-gateway:
    #     image: victorhugofranca/mybudget-gateway
    #     container_name: mybudget-gateway
    #     ports:
    #         - "8000:8000"
    #     links:
    #         - mybudget-service-registry
    #     environment:
    #         - eureka.client.serviceUrl.defaultZone=http://mybudget-service-registry:8761/eureka 
    #     logging:
    #       driver: awslogs
    #       options: 
    #         awslogs-group: mybudget-gateway
    #         awslogs-region: sa-east-1
    #         awslogs-stream-prefix: mybudget-gateway
    mybudget-core:
        image: victorhugofranca/mybudget-core
        container_name: mybudget-core
        ports:
            - "8180:8180"
        # links:
        #     - mybudget-service-registry
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq
            - eureka.client.serviceUrl.defaultZone=http://mybudget-service-registry:8761/eureka
        logging:
          driver: awslogs
          options: 
            awslogs-group: mybudget-core
            awslogs-region: sa-east-1
            awslogs-stream-prefix: mybudget-core
    mybudget-budget:
        image: victorhugofranca/mybudget-budget
        container_name: mybudget-budget
        ports:
            - "8081:8081"
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq
            - COREHOST=http://mybudget-core:8180/foo
            - eureka.client.serviceUrl.defaultZone=http://mybudget-service-registry:8761/eureka
        logging:
          driver: awslogs
          options: 
            awslogs-group: mybudget-budget
            awslogs-region: sa-east-1
            awslogs-stream-prefix: mybudget-budget