FROM alpine/git as clone
WORKDIR /app
RUN git clone https://github.com/victorpfranca/mybudget.git

FROM maven:3.5-jdk-8-alpine as build
WORKDIR /app
COPY --from=clone /app/mybudget/mybudget-gateway /app 
RUN mvn install

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /app/target/mybudget-gateway-0.0.1-SNAPSHOT.jar /app 
EXPOSE 8000
CMD ["java", "-Xmx512m", "-jar", "mybudget-gateway-0.0.1-SNAPSHOT.jar"]