server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    categories:
      path: /categories/**
      serviceId: mybudget-categories
      strip-prefix: false
    foo:
      path: /foo/**
      serviceId: mybudget-categories
      strip-prefix: false
    budgets:
      path: /budgets/**
      serviceId: mybudget-budget
      strip-prefix: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      
endpoints:
  routes:
    sensitive: false